### ISSUE TITLE
Version Bump for EM 1.2 Support

### ISSUE THREAD

**Issue by qnm** [royaltm/ruby-em-pg-client#17]
Any chance of an interim release to rubygems to support eventmachine 1.2.0+ ?

If you like, I'm happy to assist with configuring Travis to automatically create and deploy `-pre.alpha` revisions to RubyGems - they are very useful for those of use who can't use Bundler to reference GitHub.

**Comment by royaltm** [comment]
Hello,

Frankly I'm not using this gem anymore myself , so progress here is close to none. I don't really have much time to contribute here so any help would be much appreciated. Would you take a look at `.travis.yml` and make a PR perhaps or maybe just how it should be done via gist? I would gladly release it then.
